import assert from 'assert';
import { agentTeamEngine } from '../../server/agentTeam';
import { workspace } from '../../server/virtualWorkspace';
import { providerManager } from '../../server/providerManager';

export async function runJulesAgentTeamIntegrationTests() {
  console.log('\n--- [Integration Test] Team Orchestration with Autonomous Coding Agent (Jules) ---');

  providerManager.setActiveProvider('mock');
  workspace.seedDefaultFiles();

  // Test executing a workflow delegating Developer implementation to the coding agent
  const taskPrompt = 'Fix the DeepSeek provider and implement token streaming';
  const result = await agentTeamEngine.runWorkflow(
    taskPrompt,
    'tier_3',
    undefined,
    {
      provider: 'mock',
      codingAgent: 'mock',
      repository: 'MohamedGH/agentTeam',
      branch: 'main',
      automationMode: 'AUTO_CREATE_PR',
    }
  );

  assert.strictEqual(result.success, true, 'Workflow should succeed');
  assert.strictEqual(result.codingAgentUsed, 'mock');
  assert.ok(result.prUrl?.includes('pull/42'), 'Result must include PR URL generated by coding agent');
  assert.ok(result.gitBranch?.startsWith('jules/patch-'), 'Result must include git branch');

  // Verify steps timeline
  const managerSteps = result.steps.filter((s) => s.agent === 'manager');
  const developerSteps = result.steps.filter((s) => s.agent === 'developer');
  const testerSteps = result.steps.filter((s) => s.agent === 'tester');
  const reviewerSteps = result.steps.filter((s) => s.agent === 'reviewer');

  assert.ok(managerSteps.length >= 2, 'Manager steps should include Planning and Final Delivery');
  assert.ok(developerSteps.length >= 1, 'Developer steps should capture Jules coding session');
  assert.ok(testerSteps.length >= 1, 'Tester steps should validate implementation');
  assert.ok(reviewerSteps.length >= 1, 'Reviewer steps should review diff');

  // Verify Jules activities captured in developer step
  const julesStep = developerSteps.find((s) => s.phaseName.includes('Jules'));
  assert.ok(julesStep, 'Step timeline must include Jules execution step');

  // Verify final report metadata
  assert.ok(result.finalReport, 'Final report must be present');
  assert.strictEqual(result.finalReport.implementation, 'PASS');
  assert.strictEqual(result.finalReport.tests, 'PASS');
  assert.strictEqual(result.finalReport.review, 'APPROVED');
  assert.strictEqual(result.finalReport.metrics.codingAgentUsed, 'mock');
  assert.ok(result.finalReport.metrics.prUrl?.includes('pull/42'));

  console.log('✅ PASS: Autonomous coding agent orchestration fully verified with PR & branch telemetry');

  // Test direct runWithCodingAgent API
  const directResult = await agentTeamEngine.runWithCodingAgent({
    agent: 'mock',
    repository: 'MohamedGH/agentTeam',
    branch: 'main',
    task: 'Enhance rate limiting and add retry with jitter',
    automationMode: 'AUTO_CREATE_PR',
  });

  assert.strictEqual(directResult.success, true);
  assert.strictEqual(directResult.codingAgentUsed, 'mock');
  assert.ok(directResult.prUrl);
  console.log('✅ PASS: agentTeamEngine.runWithCodingAgent directly routes task to coding agent');

  // Test Failure Handling: Jules failure must halt orchestration and never be masked as success
  const failureResult = await agentTeamEngine.runWorkflow(
    'TASK_TRIGGER_FAILURE: 404 entity not found',
    'tier_3',
    undefined,
    {
      provider: 'mock',
      codingAgent: 'mock',
      repository: 'MohamedGH/agentTeam',
      branch: 'main',
    }
  );

  assert.strictEqual(failureResult.success, false, 'Workflow MUST fail when coding agent fails');
  assert.ok(failureResult.error, 'Error must be preserved in workflow result');
  
  // Verify that subsequent agents (Tester, Reviewer) WERE NOT RUN!
  const failedTesterSteps = failureResult.steps.filter((s) => s.agent === 'tester');
  const failedReviewerSteps = failureResult.steps.filter((s) => s.agent === 'reviewer');
  assert.strictEqual(failedTesterSteps.length, 0, 'Tester must NOT run when Jules agent fails');
  assert.strictEqual(failedReviewerSteps.length, 0, 'Reviewer must NOT run when Jules agent fails');

  const failedDevStep = failureResult.steps.find((s) => s.agent === 'developer' && s.status === 'STATUS: FAILED');
  assert.ok(failedDevStep, 'Jules failure step must be recorded in steps');
  assert.strictEqual(failedDevStep?.status, 'STATUS: FAILED');
  assert.strictEqual(failureResult.finalReport?.implementation, 'FAIL');
  assert.strictEqual(failureResult.finalReport?.tests, 'SKIPPED');
  assert.strictEqual(failureResult.finalReport?.review, 'SKIPPED');

  console.log('✅ PASS: Coding agent failure strictly halts team orchestration, prevents subsequent agents, and returns success=false');

  console.log('✅ Jules Team Integration Tests Passed');
}
